### ISSUE TITLE
Compress barrier images

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/next-barriers#27]
They take 20s to download on 3g

**Comment by matthew-andrews** [comment]
think just needs a bit of `{{#resize}}` and `n-image` love, it's physically quite big:-
https://next.ft.com/assets/print_digital.png

origami image service should also do some compression

**Comment by matthew-andrews** [comment]
![screen shot 2015-08-12 at 00 28 33](https://cloud.githubusercontent.com/assets/825088/9213329/17521198-4089-11e5-893c-255f2843b2a2.png)

Yup image service alone without any resizing takes it from 457kb to 105kb:-

http://ft-next-assets-prod.s3-website-eu-west-1.amazonaws.com/assets/print_digital.png
vs. http://image.webservices.ft.com/v1/images/raw/http://ft-next-assets-prod.s3-website-eu-west-1.amazonaws.com/assets/print_digital.png?source=mattatest

http://image.webservices.ft.com/v1/images/raw/http://ft-next-assets-prod.s3-website-eu-west-1.amazonaws.com/assets/print_digital.png?source=mattatest&width=400
http://image.webservices.ft.com/v1/images/raw/http://ft-next-assets-prod.s3-website-eu-west-1.amazonaws.com/assets/print_digital.png?source=mattatest&width=800

and looking at the breakpoints its biggest width is ~400px (800px retina) so if we use `n-image` and only serve 800px width images to 2x devices it'll go down to 26kb for 400px, 93kb for 800px.

**Comment by commuterjoy** [comment]
Hi @ifyio - Can you pick this one up please?

**Comment by matthew-andrews** [comment]
make sure to check out the `#resize` helper :-)

**Comment by matthew-andrews** [comment]
e.g. `<img src="{{#resize 150}}{{image}}{{/resize}}" />`

**Comment by ifyio** [comment]
Closing this now as the fix is now on live
