### ISSUE TITLE
Incorrect spelling of Martin Sandbu's name

### ISSUE THREAD

**Issue by SarahHornsey** [Financial-Times/next-barriers#37]
His name is "Martin Sandbu" not "Martin Sambu"

![image](https://cloud.githubusercontent.com/assets/8235225/9389352/97f78258-4762-11e5-864f-a2528af82add.png)

**Comment by commuterjoy** [comment]
fixed here - https://github.com/Financial-Times/next-article/pull/811

**Comment by ifyio** [comment]
Closing this as it has been fixed
