### ISSUE TITLE
Signed-in members with a registration (but not a paid subscription) cannot buy a subscription via next.ft.com. 

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/next-barriers#41]
Currently, next.ft.com visitors *can* sign up for an ft.com membership and buy a subscription *if they're not signed in*.

Signed-in members with a registration (but not a paid subscription) *cannot* get a paid subscription via next.ft.com. (At least not the same way that's set up for non-signed-in next.ft.com visitors)

**Comment by commuterjoy** [comment]
... so what do we want to happen?

**Comment by adambraimbridge** [comment]
Probably have the same experience for signed-in members as the current one for non-signed in visitors; that is, show the paywall barrier. 

I'm not familiar with the code, but @mattijas suggests we either wait for the Membership team to add case for the signed-in members to the barrier API, or default the signed-in members to use the same barrier as the non-signed in visitors.

**Comment by Lrnk** [comment]
My testing got as far as trying to reproduce this locally by npm linking next-barriers, as I believe it's this component that doesn't cover the case of being a non-premium subscriber(?). I found though that I couldn't work out how to identify what headers were being set on live that was causing the behaviour, so wasn't able to reproduce locally.

**Comment by Lrnk** [comment]
Here's a copy of my https://session-next.ft.com/ output:
```js
{
   "erightsId":"12404827",
   "passportId":"4012404827",
   "uuid":"f0bb6f11-c034-4792-a1c0-3647825363a0",
   "title":"",
   "firstName":"",
   "lastName":"",
   "emailAddress":"laurie.boyes@ft.com",
   "groups":"UK",
   "products":"P0,Tools",   
   "sessionToken":"0_C7bxHANEeS06HANkeCU2OgzwAAAU_g0P3yww.MEYCIQCzVVzAr0Yx6Agm9v3bJljBGdx7fY8U6vBExhnaqSGVcwIhAIsJ3xUf8pNucM3WTJjCv6B3pRfhCea4mz8_h6V-29-a",
   "industry":"Comms/Publishing/Media",
   "position":"Professional",
   "responsibility":"Operations"
}
```

**Comment by Lrnk** [comment]
And here's what I see when I hit an article page:

<img width="1062" alt="screen shot 2015-09-17 at 09 03 27" src="https://cloud.githubusercontent.com/assets/4622378/9990779/cf21100c-605b-11e5-9d81-05583c4aa3b3.png">

**Comment by adambraimbridge** [comment]
This issue's fixed, at least for now. If you're not signed in, and there is a response header of `FT-Barrier-Type:REGISTRATION`, then the article is served for free. This'll change once we build a registration barrier. Trial, Subscribe and Premium barriers are appearing as expected.
